version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:80

  backend:
    build:
      context: ./backend
    ports:
      - 9000:9000
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
